hmcts/finrem-evidence-management-client-api

build.gradle, src/smokeTest/java/uk/gov/hmcts/reform/emclient/smoketests/EmClientSmokeTests.java, src/smokeTest/java/uk/gov/hmcts/reform/emclient/smoketests/SmokeTestConfiguration.java, src/smokeTest/resources/application.properties
=> FR_716_smoke_tests

src/smokeTest/java/uk/gov/hmcts/reform/emclient/smoketests/EmClientSmokeTests.java, src/smokeTest/resources/application.properties
- removed harcoded connection timeout parameters.
=> FR_716_smoke_test_fix

src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementFileDeleteIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementTestUtils.java, src/main/java/uk/gov/hmcts/reform/emclient/controller/EvidenceManagementClientController.java, src/main/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDeleteService.java, src/main/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDeleteServiceImpl.java, src/test/java/uk/gov/hmcts/reform/emclient/controller/EvidenceManagementClientControllerTest.java, src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDeleteServiceImplTest.java
=> adding delete endpoint

Jenkinsfile_CNP, charts/finrem-emca/Chart.yaml, charts/finrem-emca/requirements.yaml, charts/finrem-emca/values.aat.template.yaml, charts/finrem-emca/values.preview.template.yaml, charts/finrem-emca/values.yaml
=> Implement Helm Charts.

build.gradle, src/main/resources/application.properties
- reduced endpoint cache time to live to 1000ms
https://tools.hmcts.net/jira/browse/FR-819
Health endpoint caching issue
```
[ ] Yes
[X] No
```
=> FR_819_health_endpoint_cache_issue

build.gradle, dependency-check-suppressions.xml, src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementFileDownloadIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/emclient/controller/EvidenceManagementClientController.java, src/main/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDownloadService.java, src/main/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDownloadServiceImpl.java, src/test/java/uk/gov/hmcts/reform/emclient/controller/EvidenceManagementClientControllerTest.java, src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDeleteServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDownloadServiceImplTest.java
=> FR-862: File download api

src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementFileDownloadIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementTestUtils.java, src/integrationTest/resources/application.properties
=> fileupload test evidence management

build.gradle, dependency-check-suppressions.xml, gradle/wrapper/gradle-wrapper.properties, src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/ServiceContextConfiguration.java, src/test/java/uk/gov/hmcts/reform/emclient/health/WebServiceHealthCheckTest.java, src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDeleteServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementUploadServiceImplTest.java
=> fixing dependencies

charts/finrem-emca/values.yaml, web.config
=> Fixing chart

build.gradle, dependency-check-suppressions.xml, gradle/wrapper/gradle-wrapper.properties, gradlew, gradlew.bat, src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementFileDeleteIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementFileDownloadIntegrationTest.java, src/integrationTest/resources/application-aat.properties, src/integrationTest/resources/application.properties, src/main/java/uk/gov/hmcts/reform/emclient/configuration/EvidenceManagementClientConfiguration.java, src/main/java/uk/gov/hmcts/reform/emclient/configuration/SwaggerConfiguration.java, src/main/java/uk/gov/hmcts/reform/emclient/controller/EvidenceManagementClientController.java, src/main/java/uk/gov/hmcts/reform/emclient/errorhandler/GlobalExceptionHandler.java, src/main/java/uk/gov/hmcts/reform/emclient/health/DefaultHttpEntityFactory.java, src/main/java/uk/gov/hmcts/reform/emclient/idam/services/UserService.java, src/main/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDeleteServiceImpl.java, src/main/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementUploadServiceImpl.java, src/main/resources/application.properties, src/test/java/uk/gov/hmcts/reform/emclient/functional/BaseFunctionalTest.java, src/test/java/uk/gov/hmcts/reform/emclient/functional/HealthCheckFunctionalTest.java, src/test/java/uk/gov/hmcts/reform/emclient/health/DefaultHttpEntityFactoryTest.java, src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDeleteServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementUploadServiceImplTest.java
=> Updating gradle

infrastructure/variables.tf
=> Removing client id

infrastructure/main.tf
=> Fixing terraform issues

build.gradle
=> Updating logging dependencies

README.md, build.gradle
https://tools.hmcts.net/jira/browse/RPET-177
Updating the config file by adding required swagger library resolved issue.
```
[ ] Yes
[x] No
```
=> Fix Swagger for FR Evidence Management Service

src/main/java/uk/gov/hmcts/reform/emclient/configuration/EvidenceManagementClientConfiguration.java
=> Changing package name

src/main/java/uk/gov/hmcts/reform/emclient/configuration/EvidenceManagementClientConfiguration.java
=> Supporting both HAL types

Dockerfile, audit.json, build.gradle
=> update tomcat version and ignore cookie errors

audit.json
=> add false positives

build.gradle, dependency-check-suppressions.xml, gradle/wrapper/gradle-wrapper.properties
=> upgrade versions

charts/finrem-emca/Chart.yaml, charts/finrem-emca/requirements.yaml
https://tools.hmcts.net/jira/browse/FR-1981
Upgrades Helm chart API to v2
```
[ ] Yes
[x] No
```
=> Upgrade Helm chart API version to v2

build.gradle, charts/finrem-emca/Chart.yaml, src/main/resources/application.properties
https://tools.hmcts.net/jira/browse/FR-1984
Updates base chart to latest version
```
[ ] Yes
[x] No
```
=> Update base chart to latest version

Jenkinsfile_CNP, build.gradle, src/contractTest/java/uk/gov/hmcts/reform/finrem/evidencemanagement/clientapi/contracts/dmstore/EvidenceManagementDeleteServiceConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/finrem/evidencemanagement/clientapi/contracts/dmstore/EvidenceManagementDownloadServiceConsumerTest.java, src/contractTest/resources/application-contract.properties, src/main/java/uk/gov/hmcts/reform/emclient/EvidenceManagementClientApplication.java, src/main/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementUploadServiceImpl.java, src/test/java/uk/gov/hmcts/reform/emclient/BaseTest.java
TA-395 Pact Consumer Tests for dm-store interactions
=> TA-395 Pact Consumer Tests for dm-store interactions

Jenkinsfile_CNP
=> TA-395: Fix Pact Phase in jenkins

audit.json
No code changes- just ignore false positives.
=> ignore zap false positives

build.gradle
=> fix dependency check issue

README.md, build.gradle, charts/finrem-emca/Chart.yaml, src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/IdamUtils.java
https://tools.hmcts.net/jira/browse/DFR-76
=> DFR-76 SpringBoot Update

build.gradle, charts/finrem-emca/Chart.yaml
https://tools.hmcts.net/jira/browse/DFR-568
```
[ ] Yes
[ x] No
```
=> Dfr 568 fix glassfish vulne

Jenkinsfile_nightly, build.gradle, config/fortify-client.properties, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DFR-472
https://tools.hmcts.net/jira/browse/DFR-472
```
[ ] Yes
[ x] No
```
=> Integrate Fortify

src/main/resources/application.properties
DFR-472
Remove mgmt endpoints security set to false
```
[ ] Yes
[ x] No
```
=> DFR-472: Fix fortify issues

build.gradle, charts/finrem-emca/Chart.yaml
fix- vulnerabilities
bump chart version
removed deprecated jcente
=> fix vul, chart and removed deprecated jcenter

charts/finrem-emca/Chart.yaml
=> bump chart

build.gradle, charts/finrem-emca/Chart.yaml
>     bump java chart version
>     fix jackson vulnerability
=> fix jackson vulnerability and bump java chart version

build.gradle, dependency-check-suppressions.xml
CVE-2020-36518: fix jackson vulnerability
=> CVE-2020-36518: fix jackson vulnerability

build.gradle
=> bump springframework

build.gradle
=> updating CVE ref

build.gradle, dependency-check-suppressions.xml, src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementFileDeleteIntegrationTest.java
https://tools.hmcts.net/jira/browse/DFR-1003
```
[ ] Yes
[ x] No
```
=> DFR-1003: Fix failing integration test

Dockerfile, acb.tpl.yaml
https://tools.hmcts.net/jira/browse/DFR-1052
=> DFR-1052 added multi arch docker image

charts/finrem-emca/Chart.yaml, charts/finrem-emca/values.yaml
https://tools.hmcts.net/jira/browse/DTSSE-1394
```
[ ] Yes
[ ] No
```
=> Add Autoscaling Create values.yaml

build.gradle, dependency-check-suppressions.xml
=> Bumping Springframework

.github/renovate.json
[DFR-1162](https://tools.hmcts.net/jira/browse/DFR-1162)
Enable Renovate for automatic software updates
```
[ ] Yes
[ ] No
```
=> DFR-1162: Enable renovate

charts/finrem-emca/Chart.yaml
DFR-1211
updated java chart version
```
[ ] Yes
[x] No
```
=> DFR-1211: updated java chart version

Jenkinsfile_nightly, charts/finrem-emca/Chart.yaml, charts/finrem-emca/values.yaml, src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EmClientFileUploadTest.java, src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementFileAuditIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementFileDeleteIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementFileDownloadIntegrationTest.java, src/integrationTest/resources/application.properties
DFR-1300
fix ft
```
[ ] Yes
[x] No
```
=> DFR-1300: fix ft

audit.json
N/A
fix security scan failure
```
[ ] Yes
[x] No
```
=> DFR-1300: fix security scan

build.gradle
=> fix snakeyml dep

build.gradle
=> Upgrade SnakeYMl 1.33

dependency-check-suppressions.xml
=> Suppressing Jackson-databind

build.gradle
Modified Tomcat version
```
[ ] Yes
[X] No
```
=> Fix dependency issue - modified Tomcat version from 9.0.63 to 9.0.68

dependency-check-suppressions.xml
=> Tidying suppressions file

dependency-check-suppressions.xml
=> Suppressing apache commons

dependency-check-suppressions.xml
=> Suppressing bad CVE

dependency-check-suppressions.xml
=> Suppressing snakeyaml dependency

build.gradle, dependency-check-suppressions.xml
=> Apache Commons bumps

charts/finrem-emca/Chart.yaml, src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementFileDeleteIntegrationTest.java
DFR-1758
update-chart-version
```
[ ] Yes
[ ] No
```
=>  DFR-1758: update-chart-version

charts/finrem-emca/Chart.yaml
[DFR-1783](https://tools.hmcts.net/jira/browse/DFR-1783)
Upgrade charts
```
[ ] Yes
[ x] No
```
=> DFR-1783: Upgrade charts

build.gradle, dependency-check-suppressions.xml
=> upgrade owasp dependency

dependency-check-suppressions.xml
=> dependency patch
